# Generated by Django 4.0.4 on 2022-04-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrado',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
